# Generated by Django 5.1.2 on 2025-01-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfilprivado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
