# Generated by Django 5.1.2 on 2025-01-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_perfilprivado_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fechadenacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfilprivado',
        ),
    ]
