# Generated by Django 5.1.2 on 2025-01-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('AR', 'Argentina'), ('ES', 'España'), ('IT', 'Italia'), ('FR', 'Francia')], null=True),
        ),
    ]
