# Generated by Django 5.1.2 on 2025-01-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
