# Generated by Django 5.1.2 on 2025-02-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_amistad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='juegoprimero',
            field=models.CharField(blank=True, choices=[('CSGO2', 'Csgo2'), ('ROCKET LEAGUE', 'Rocketleague'), ('GTAV', 'Gtav'), ('MINECRAFT', 'Minecraft'), ('DONT STARVE TOGETHER', 'Dst')], null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='juegosegundo',
            field=models.CharField(blank=True, choices=[('CSGO2', 'Csgo2'), ('ROCKET LEAGUE', 'Rocketleague'), ('GTAV', 'Gtav'), ('MINECRAFT', 'Minecraft'), ('DONT STARVE TOGETHER', 'Dst')], null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='juegotercero',
            field=models.CharField(blank=True, choices=[('CSGO2', 'Csgo2'), ('ROCKET LEAGUE', 'Rocketleague'), ('GTAV', 'Gtav'), ('MINECRAFT', 'Minecraft'), ('DONT STARVE TOGETHER', 'Dst')], null=True),
        ),
    ]
