# Generated by Django 5.1.2 on 2025-02-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_usuario_juegoprimero_usuario_juegosegundo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='juegosegundo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='juegotercero',
        ),
    ]
