# Generated by Django 5.1.2 on 2025-02-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_usuario_juegosegundo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='juegoprimero',
            field=models.CharField(choices=[('CSGO2', 'Csgo2'), ('ROCKETLEAGUE', 'Rocketleague'), ('GTAV', 'Gtav'), ('MINECRAFT', 'Minecraft'), ('DONTSTARVETOGETHER', 'Dst')], default='CSGO2'),
        ),
    ]
