# Generated by Django 5.1.2 on 2025-02-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_usuario_juegoprimero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='niveljuego',
            field=models.CharField(default='', max_length=50),
        ),
    ]
