# Generated by Django 5.1.2 on 2025-01-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_usuario_edad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
