# Generated by Django 5.1.1 on 2024-11-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('fechadenacimiento', models.DateField(blank=True, null=True)),
                ('posicionglobal', models.IntegerField(blank=True, null=True)),
                ('adr', models.FloatField(blank=True, null=True)),
                ('kda', models.FloatField(blank=True, null=True)),
                ('headshots', models.FloatField(blank=True, null=True)),
                ('dpr', models.FloatField(blank=True, null=True)),
                ('wr', models.FloatField(blank=True, null=True)),
                ('kast', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
