# Generated by Django 5.1.2 on 2025-01-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_perfilprivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfilprivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
