# Generated by Django 5.1.2 on 2025-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('AR', 'Argentina'), ('ES', 'España'), ('IT', 'Italia'), ('FR', 'Francia')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
