# Generated by Django 5.1.2 on 2025-01-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(choices=[('AR', 'Argentina'), ('ES', 'España'), ('IT', 'Italia'), ('FR', 'Francia')], default='AR'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
