# Generated by Django 5.1.2 on 2025-01-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usuario_nacionalidad_alter_usuario_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nacionalidad',
        ),
    ]
