# Generated by Django 5.1.2 on 2025-01-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_usuario_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(choices=[('AR', 'Argentina'), ('ES', 'España'), ('IT', 'Italia'), ('FR', 'Francia')], default='AR'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
