# Generated by Django 5.1.2 on 2025-02-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_usuario_niveljuego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='niveljuego',
            new_name='juegoprimeronivel',
        ),
    ]
