# Generated by Django 5.1.2 on 2025-10-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_niveljuego_usuario_juegoprimeronivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='juegoprimero',
            field=models.CharField(choices=[('CSGO2', 'Csgo2'), ('ROCKETLEAGUE', 'Rocketleague'), ('GTAV', 'Gtav'), ('MINECRAFT', 'Minecraft'), ('DONTSTARVETOGETHER', 'Dst'), ('FIFA', 'Fifa'), ('FORTNITE', 'Fortnite'), ('RAINBOW6', 'Rainbow6')], default='CSGO2', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(choices=[('AR', 'Argentina'), ('ES', 'España'), ('IT', 'Italia'), ('FR', 'Francia')], default='AR', max_length=20),
        ),
    ]
